ktor:
  development: true
  application:
    modules:
      - com.dennisdevelops.ApplicationKt.module
  deployment:
    watch:
      - classes
      - resources
    # Port 8080 or from environment variable
    port: "$PORT:8080"

auth:
  sessions:
    encryptionKey: "$SESSION_ENCRYPTION_KEY"
    decryptionKey: "$SESSION_DECRYPTION_KEY"

